# Generated by Django 5.2.5 on 2025-09-09 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='sentiment',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
